plugins: musicbrainz edit scrub embedart missing info fetchart convert
directory: /home/callum/Music/
import:
  move: yes
  language: en
  from_scratch: yes
embedart:
  auto: no
fetchart:
  auto: no
convert:
  format: aac
  formats:
    aac:
      command: ffmpeg -i $source -y -c:a aac -b:a 256k $dest
      extension: m4a
  embed: yes
  copy_album_art: yes
  never_convert_lossy_files: yes

