plugins: scrub edit embedart missing info fetchart
directory: /mnt/c/Users/Callum/Music/data
import:
  move: yes
  language: en
  from_scratch: yes
embedart:
  auto: no
fetchart:
  auto: no
  sources: filesystem coverart itunes amazon albumart
