plugins: musicbrainz scrub edit embedart missing info fetchart convert
directory: /home/callumjones/Music
import:
  move: yes
  language: en
  from_scratch: yes
embedart:
  auto: no
fetchart:
  auto: no
  sources: filesystem coverart itunes amazon albumart
convert:
  format: opus
  formats:
    opus: ffmpeg -i $source -y -vn -acodec libopus -ab 128k $dest
  embed: no
  copy_album_art: yes
