plugins: musicbrainz scrub edit embedart missing info fetchart convert
directory: /mnt/c/Users/Callum/Music/data
import:
  move: yes
  language: en
  from_scratch: yes
embedart:
  auto: no
fetchart:
  auto: no
  sources: filesystem coverart itunes amazon albumart
convert:
  format: aac
  formats:
    aac:
      command: ffmpeg -i $source -y -c:a libfdk_aac -b:a 256k $dest
      extension: m4a
  embed: yes
  copy_album_art: yes
  never_convert_lossy_files: yes

