theme = "adwaita-dark"

[editor]
auto-pairs = false
mouse = false
auto-completion = true
line-number = "relative"
completion-timeout = 5
color-modes = true
true-color = true
undercurl = true
rulers = [80]
popup-border = "all"
rainbow-brackets = true
end-of-line-diagnostics = "disable"
shell = ["bash", "-c"]

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.insert]
"C-e" = "@<esc>hv<S-F><lt>\"zy\"zpi<esc>;a/<esc>i"
