# ############################################
#
# Language Server configs
#
# ############################################

[language-server.typescript-language-server]
command = "typescript-language-server"
timeout = 120
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

# ############################################
#
# Language configurations
#
# ############################################

# Configure Pythono with PyLSP as the default LSP (installed globally),
# attempt to use ruff for linting and formattin (installed @ project level),
# attempt to use pyright for type checking (installed @ project level).
[[language]]
name = "python"
language-servers = [  "ruff", "pyright" ]
auto-format = true
rulers = [88]

[language.formatter]
command = "ruff"
args = ["format", "-"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "javascript"
language-servers = [
  "vscode-eslint-language-server",
  "vtsls",
]

[[language]]
name = "jsx"
language-servers = [
  "vtsls",
  "vscode-eslint-language-server",
  "tailwindcss-ls",
]

[[language]]
name = "typescript"
language-servers = [
  "vtsls",
  "vscode-eslint-language-server",
]

[[language]]
name = "tsx"
language-servers = [
  "vtsls",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
]

[[language]]
name = "markdown"
soft-wrap.enable = true
